export const LAST_LOCATION = 'LAST_LOCATION'
export const SET_ORIGIN = 'SET_ORIGIN'
export const SET_ORIGIN_LOCATIONS = 'SET_ORIGIN_LOCATIONS'
export const SET_DESTINATION_LOCATIONS = 'SET_DESTINATION_LOCATIONS'
