export default {
  // svgArea: { w:1200, h:900 },
  svgBgColor: '#fff',
  svgMargin: 50,
  pathStrokeThickness: 2,
  pathStrokeColor: '#006CC4',
  originDotColor: '#006CC4',
  originCircleColor: '#000',
  originDotSize: 5,
  originCircleSize: 8,
  originLabelFontSize: '8px',
  destinationDotColor: '#000',
  destinationLabelFontSize: '8px',
  destinationDotSize: 3,
}
