export default {
  // svgArea: { w:1200, h:900 },
  svgBgColor: '#fff',
  svgMargin: 100,
  pathStrokeThickness: 2,
  pathStrokeColor: '#006CC4',
  originDotColor: '#006CC4',
  originCircleColor: '#000',
  originDotSize: 4,
  originCircleSize: 6,
  originLabelFontSize: '1.25rem',
  destinationDotColor: '#000',
  // destinationLabelFontSize: '8px',
  destinationDotSize: 3,
}
